### ISSUE TITLE
Fix CSP issues

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/airmo-project#12]
The initial set of CSP rules is missing some stuff. Let's re-do the CSP discovery process (using the FF extension), ensuring that we click on everything, performksome searches, play some videos, really try and exercise every feature of the site that we can find.

**Comment by joekrejci** [comment]
Re-worked the CSP, clicked every link I could find, followed links, etc. Should be good to go now. Merged a PR with updated CSP.
