### ISSUE TITLE
Move to appsvcs-generic

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/airmo-project#2]
Can we put this in `appsvcs-generic`?

What are our other options?

I heard mention of `it-avops` which might also work.

**Comment by mgreensmith** [comment]
The staging version is deployed in nubis-training, it (and eventually the prod version) needs to move to appsvcs-generic.

**Comment by mgreensmith** [comment]
Please change the service name too. https://github.com/mozilla-itcloud/air.mozilla.org/blob/master/nubis/terraform/terraform.tfvars#L5

**Comment by mgreensmith** [comment]
@joekrejci I see that https://github.com/mozilla-itcloud/air.mozilla.org/pull/10 also includes some mention of moving the app to appsvcs-generic. Has this happened?

**Comment by joekrejci** [comment]
@mgreensmith Yup moved it over yesterday, Ill close this issue out.
