### ISSUE TITLE
Implement scraper cron job

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/airmo-project#4]
The app has a cron job that scrapes the private AirMo content into its DB. We need to implement this in nubis.

**Comment by mgreensmith** [comment]
At least every 30 min, but preferably more frequently if execution time is low.

**Comment by mgreensmith** [comment]
https://github.com/mozilla-itcloud/air.mozilla.org/pull/10

**Comment by joekrejci** [comment]
manage.py implemented via /nubis/puppet/cron.pp
