### ISSUE TITLE
Add CSP and HSTS Headers

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/airmo-project#6]
EIS performed a vulnerability assessment of the airmo app: https://bugzilla.mozilla.org/show_bug.cgi?id=1461279

We need to pull out action items (e.g. "add CSP headers") and enumerate them here.

Then we'll figure out which ones need to be resolved before we launch.

**Comment by mgreensmith** [comment]
Results from VA:

- Overall, not too bad. There are a couple glaring issues, such as lack of SSL, but it could be attributed to being a dev site.
  Recommendation: Get a proper certificate and ensure the traffic is defaulted to HTTPS on the production site. Once implemented, configure it as per https://infosec.mozilla.org/guidelines/web_security.html#transport-layer-security-tlsssl.

- Web security standards are not followed (see Observatory score in comment 3). 
  Recommendation: We'd like the see the site implementing a content security policy, HSTS and HTTP->HTTPS redirection (to enforce HTTPS at all times) at the very least.

- If not required in production site, disable SSH service altogether. If required, configure the SSH service as per https://infosec.mozilla.org/guidelines/openssh.html#openssh-server. At the very least ensure password authentication is disabled, and consider alternatives (such as public key authentication, or multi-factor authentication).

**Comment by mgreensmith** [comment]
The only outstanding issue here afaik will be adding CSP and HSTS headers.

**Comment by joekrejci** [comment]
Waiting on Approval and Merge....
https://github.com/mozilla-itcloud/air.mozilla.org/pull/14

**Comment by joekrejci** [comment]
CSP Header and HSTS set: 


➜  ~ curl -Ik  https://www.airmofront.stage.core.us-west-2.appsvcs-generic.nubis.allizom.org/
HTTP/1.1 200 OK
Content-Length: 17789
Content-Security-Policy: default-src 'none'; font-src https://fonts.gstatic.com; img-src 'self' https://onlinexperiences.com https://www.google-analytics.com; script-src 'self' 'unsafe-inline' https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtm.js; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://onlinexperiences.com;
Content-Type: text/html; charset=utf-8
Date: Fri, 22 Jun 2018 16:35:13 GMT
Server: Apache/2.4.18 (Ubuntu)
strict-transport-security: max-age=86400
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Nubis-Build: amazon-ebs-ubuntu
X-Nubis-Project: airmofront
X-Nubis-Version: v2.2.0_de6e0c1e062465f864a5a728a6159ce22d1007a8
x-xss-protection: 1; mode=block
Connection: keep-alive
